### ISSUE TITLE
"Download More" option redirects to 404 Page Not Found

### ISSUE THREAD

**Issue by jwaisner** [Bearsampp/Bearsampp#141]
### Behaviour
When clicking "download more" it redirects to a 404 page.

![image](https://user-images.githubusercontent.com/12568201/182248032-92d01e73-d9f7-4847-ae02-38515defcb50.png)

![image](https://user-images.githubusercontent.com/12568201/182247971-7b8f4147-6883-4f86-9373-421f1e2309cb.png)

#### Steps to reproduce this issue

1. Go to Localhost
2. Click the "download more" option beside any binary tool or application
3. Page redirects to 404 page

#### Expected behaviour

> Should redirect to the correct page with other downloadable modules/tools

#### Actual behaviour

> Redirects to 404 Page Not Found

### Configuration

* Bearsampp version and the previous version in case of upgrade:  August Release
* Operating system: Windows 11 x64

**Comment by N6REJ** [comment]
So this is caused by invalid link format.  I don't completely understand the structure yet.
https://bearsampp.com/modules/gitlist/?utm_source=bearsampp-2022.08.01#releases
where the "gitlist" is changed for each item.  I'm not sure whats considered a "utm" and whats not.
![image](https://user-images.githubusercontent.com/1850089/182267769-5baf9ced-3e11-41b7-8d9c-773ead2bcb3b.png)
I believe is the relevant section.

**Comment by N6REJ** [comment]
yarn, for example, should point to https://github.com/Bearsampp/module-yarn/releases

**Comment by N6REJ** [comment]
bringing it up in phpstorm returns
![image](https://user-images.githubusercontent.com/1850089/182268054-f0f5b17b-521b-4bbf-9959-ec1e08512ae1.png)
