### ISSUE TITLE
Change default consolez font  to  Jetbrains Nerd mono font

### ISSUE THREAD

**Issue by N6REJ** [Bearsampp/Bearsampp#216]
lets switch to Jetbrains nerd mono font since its a nice clean font and works with oh-my-posh.
Lets also get rid of the red text at the beginning of the path.

**Comment by N6REJ** [comment]
https://github.com/chrisant996/clink/discussions/341

**Comment by N6REJ** [comment]
He gave us the answer we needed and I created a new bin called 2022.09.11 but for some dumb reason it won't build with updated files https://github.com/Bearsampp/modules-untouched/releases/tag/consolez-2022.09.11
I can't quite figure out the folder structure its looking for.
This is the actual clink repo source file.

[clink.1.3.42.ef446e.zip](https://github.com/Bearsampp/Bearsampp/files/9542268/clink.1.3.42.ef446e.zip)

**Comment by ihackcode** [comment]
I was able to get an output. Here is the folder I used for module-consolez/bin/consolez2022.09.11 
[consolez2022.09.11.zip](https://github.com/Bearsampp/Bearsampp/files/9694338/consolez2022.09.11.zip)

Also note that the clink.1.3.42.zip (in deps.properties) I uploaded is different. I had to create a folder in it. So that it would extract the files to the folder named "clink.1.3.42".

and the output files it created. (I had to put it in a zip to upload it to this message)
[output.zip](https://github.com/Bearsampp/Bearsampp/files/9694343/output.zip)

Also, delete the files in the 'bearsampp-build\tmp\dl' folder as it won't download the new files with the same name.

Hope this helps.

**Comment by N6REJ** [comment]
thanks for your efforts, we'll be taking a look at this soon.

**Comment by jwaisner** [comment]
@ihackcode , thank you for working on this. Can you please follow the steps outlined in the below link so we can see what changes were made and it will create a PR we can then test with?

https://bearsampp.com/contribute

I will say with the output file provided it looks like the font isnt quite coming over nicely, but this could be the way the file was setup. Once we have a branch we can help test more thoroughly.

![image](https://user-images.githubusercontent.com/12568201/194993260-a4da2d96-5797-41c0-b8b0-c323825f5caa.png)

**Comment by ihackcode** [comment]
I've forked the module-consolez font branch and made the change to the deps.properties. https://github.com/Bearsampp/module-consolez/pull/11

**Comment by N6REJ** [comment]
nice attempted at hacking
