### ISSUE TITLE
Serviced enabled / Disabled icons are not clear

### ISSUE THREAD

**Issue by shoulders** [Bearsampp/Bearsampp#281]
**Is your feature request related to a problem? Please describe.**
After an initial install I found the load up slow so i decided to disable services I did not need. I clicked on the traffic light icon, then `node.js` and clicked `Enable/Disable` a small window opened at the bottom saying `loading` and then it finished.
![image](https://user-images.githubusercontent.com/319997/201718121-d4c24c64-7e85-4f3b-8760-4ed889ac5f3c.png)

I went back to the menu and `Node.js` has a red dot on it. I cannot tell if this means it is running of if it is disabled.
![image](https://user-images.githubusercontent.com/319997/201718010-c89e0eb9-3090-4d91-b2bb-d7fa4818f81c.png)

I also then clicked on `stop all services` and rechecked the menu and the `Node.js` and `MySQL` still had the red dot on and nothing had changed.

**Describe the solution you'd like**
- If the red dot represents the service is stopped, then I would change this to a red cross. The dot could me it is active whereas you know where you stand with a cross
- Potentially I would also like the `Enable/Disable` menu item swapped for `Enable` or `Disable` and should be context aware.
- When a service is running it should should a green tick

![image](https://user-images.githubusercontent.com/319997/201720503-71edccab-324f-4d54-aac3-56d222aead96.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by N6REJ** [comment]
Load time is slow, especially with mysql.  We are loading 8G worth of data so in a "FULL" install with everything enabled this takes a while.
Without hiring a delphi developer or rewriting the entire launcher, which also means 99% of the program, there is little we can do about it.  We sped up the launch time of local host last month by over 500%.
I thought we had an article explaining the traffic lights but I can't find it so that probably means it needs to be in a more prominent spot.

Red dot does infact mean its not running OR is unavailable in that build.
@jwaisner perhaps red dots = service stopped, red X = service disabled.  
I think adding the green could be confusing as there are many more functions available to most modules then simply on/off.

Context aware verbiage is not possible without delphi rewrite as far as I know.

**Comment by N6REJ** [comment]
I knew it was there somewhere LOL https://bearsampp.com/faq/troubleshooting/why-bearsampp-icon-in-the-system-tray-is-yellow-or-red

**Comment by shoulders** [comment]
what is the point in posting issue if you guys are just going to auto close them.

**Comment by N6REJ** [comment]
we discussed this but I don't remember what our decision was.  We'll discuss it again

**Comment by N6REJ** [comment]
we cannot implement this at this time due to not having original delphi source files.
